name: CI/CD DevOps

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build y Push Docker Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: alex281205/hola-mundo-devops:latest

  deploy-to-render:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
